### ISSUE TITLE
libxml2 build problem

### ISSUE THREAD

**Issue by codaman** [swisspol/GCDWebServer#276]
i can compile with xcode 7.2 after new all xcode version i cant compile.

Undefined symbols for architecture arm64:
  "_xmlReadMemory", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebDAVServer.o
      -[GCDWebDAVServer(Methods) performLOCK:] in GCDWebDAVServer.o
  "_xmlStrcmp", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebDAVServer.o
      __XMLChildWithName in GCDWebDAVServer.o
  "_xmlFreeDoc", referenced from:
      -[GCDWebDAVServer(Methods) performPROPFIND:] in GCDWebDAVServer.o
      -[GCDWebDAVServer(Methods) performLOCK:] in GCDWebDAVServer.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by swisspol** [comment]
See getting started in README.

**Comment by codaman** [comment]
yes i've already read. i did everything

i added $(SDKROOT)/usr/include/libxml2 to header search paths
there is no libxml2 in xcode8 lib folder. i copied it to this folder.
i added lxml2 to other linker folder.

i is working on xcode 7.2 but not working on latest xcode. Please help me. Try to build it on xcode 8. i did everything step by step. It is so important for me.

Thank you

**Comment by swisspol** [comment]
The Xcode project in the repo builds fine against Xcode 8.1, there are no libxml issues. I suggest your look at all the build settings in its project / targets and make sure yours match.

**Comment by codaman** [comment]
Very thanks i solved it. i copied libxml2.dylib in xcode8 lib folder. i removed it and i used libxml2.tdb instead of libxml2.dylib.
